# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved
#

language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: cargo

