version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/rust:buster
    steps:
      - checkout
      - run: cargo test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
