name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: "Build '${{ matrix.rust }}' on ${{ matrix.os.github-name }}"
    runs-on: ${{ matrix.os.github-name }}
    strategy:
      matrix:
        os:
          - human-os-name: Linux
            github-os-name: ubuntu-latest
            meldtool-filename: meldtool
          - human-os-name: Windows
            github-os-name: windows-latest
            meldtool-filename: meldtool.exe
          - human-os-name: MacOS
            github-os-name: macOS-latest
            meldtool-filename: meldtool
        rust: [stable]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - name: Test
        run: cargo test --release
      - name: Build
        run: cargo build --release
      - name: Upload
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.os.meldtool-filename}}
          asset_name: ${{ matrix.os.meldtool-filename }}-${{ matrix.os.human-os-name }}-x64
          tag: ${{ github.ref }}
          overwrite: true
